version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: users_db
      DB_PORT: 5432
    ports:
      - "18080:18080"
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: ["go", "run", "."]

#  rabbitmq:
#    image: "rabbitmq:management"
#    ports:
#      - "15672:15672"  # Management UI
#      - "45678:5672"
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: password

volumes:
  postgres-data:

